-- =====================================================================
--  SIGEM - Sistema Integral de Gestión de Flotas y Maquinaria
--  TRANSMAQ SUR S.A.C. - Esquema inicial (PostgreSQL)
--  Flyway ejecuta este script automáticamente al iniciar la aplicación.
--  También puede ejecutarse manualmente desde pgAdmin 4 (Query Tool).
-- =====================================================================

-- Roles del sistema
create table rol (
    id bigint generated by default as identity,
    nombre varchar(50) not null unique,
    descripcion varchar(200),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table rol is 'Roles del sistema';

-- Permisos (MODULO_VER / MODULO_GESTIONAR) de cada rol
create table rol_permiso (
    rol_id bigint not null,
    permiso varchar(60) not null,
    primary key (rol_id, permiso)
);
comment on table rol_permiso is 'Permisos (MODULO_VER / MODULO_GESTIONAR) de cada rol';

-- Conductores, operadores, técnicos y personal administrativo
create table empleado (
    id bigint generated by default as identity,
    dni varchar(8) not null unique,
    nombres varchar(80) not null,
    apellidos varchar(80) not null,
    cargo varchar(30) not null,
    area varchar(30) not null,
    telefono varchar(20),
    email varchar(120),
    direccion varchar(200),
    fecha_ingreso date,
    licencia_numero varchar(20),
    licencia_categoria varchar(10),
    licencia_vencimiento date,
    estado varchar(20) not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table empleado is 'Conductores, operadores, técnicos y personal administrativo';

-- Usuarios con acceso al sistema
create table usuario (
    id bigint generated by default as identity,
    username varchar(50) not null unique,
    password varchar(100) not null,
    nombre_completo varchar(120) not null,
    email varchar(120),
    activo boolean not null,
    rol_id bigint not null,
    empleado_id bigint,
    ultimo_acceso timestamp(6),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table usuario is 'Usuarios con acceso al sistema';

-- Clientes: constructoras, mineras, gobiernos locales
create table cliente (
    id bigint generated by default as identity,
    tipo_documento varchar(20) not null,
    numero_documento varchar(11) not null unique,
    razon_social varchar(150) not null,
    tipo_cliente varchar(30) not null,
    direccion varchar(200),
    telefono varchar(20),
    email varchar(120),
    activo boolean not null,
    observaciones varchar(1000),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table cliente is 'Clientes: constructoras, mineras, gobiernos locales';

-- Personas de contacto de cada cliente
create table contacto (
    id bigint generated by default as identity,
    cliente_id bigint not null,
    nombres varchar(120) not null,
    cargo varchar(80),
    telefono varchar(20),
    email varchar(120),
    principal boolean not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table contacto is 'Personas de contacto de cada cliente';

-- Campañas de marketing
create table campana (
    id bigint generated by default as identity,
    nombre varchar(120) not null,
    canal varchar(30) not null,
    fecha_inicio date not null,
    fecha_fin date not null,
    presupuesto numeric(12,2),
    estado varchar(20) not null,
    publico_objetivo varchar(200),
    descripcion varchar(1000),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table campana is 'Campañas de marketing';

-- Solicitudes de servicio de los clientes
create table solicitud (
    id bigint generated by default as identity,
    codigo varchar(20) unique,
    cliente_id bigint not null,
    contacto_id bigint,
    fecha_solicitud date not null,
    tipo_servicio varchar(20) not null,
    tipo_unidad varchar(30),
    cantidad_unidades integer not null check (cantidad_unidades>=1),
    fecha_inicio date not null,
    fecha_fin date not null,
    origen varchar(200),
    destino varchar(200),
    descripcion varchar(1000) not null,
    estado varchar(20) not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table solicitud is 'Solicitudes de servicio de los clientes';

-- Oportunidades comerciales (embudo de ventas)
create table oportunidad (
    id bigint generated by default as identity,
    titulo varchar(150) not null,
    cliente_id bigint not null,
    campana_id bigint,
    tipo_servicio varchar(20) not null,
    etapa varchar(20) not null,
    monto_estimado numeric(12,2),
    probabilidad integer not null check ((probabilidad<=100) and (probabilidad>=0)),
    fecha_cierre_estimada date,
    responsable_id bigint,
    descripcion varchar(1000),
    solicitud_id bigint,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table oportunidad is 'Oportunidades comerciales (embudo de ventas)';

-- Maquinaria y flota (vehículos y maquinaria pesada)
create table unidad (
    id bigint generated by default as identity,
    codigo varchar(20) not null unique,
    tipo varchar(30) not null,
    marca varchar(60) not null,
    modelo varchar(60) not null,
    anio integer check ((anio<=2100) and (anio>=1970)),
    placa varchar(10),
    numero_serie varchar(60),
    capacidad varchar(60),
    estado varchar(20) not null,
    lectura_actual numeric(12,1) not null,
    intervalo_mantenimiento numeric(12,1) not null,
    lectura_ultimo_mantenimiento numeric(12,1) not null,
    tarifa_hora numeric(10,2),
    tarifa_dia numeric(10,2),
    tarifa_km numeric(10,2),
    fecha_adquisicion date,
    vencimiento_soat date,
    vencimiento_revision_tecnica date,
    observaciones varchar(1000),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table unidad is 'Maquinaria y flota (vehículos y maquinaria pesada)';

-- Almacenes de repuestos
create table almacen (
    id bigint generated by default as identity,
    nombre varchar(80) not null unique,
    ubicacion varchar(200),
    responsable_id bigint,
    activo boolean not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table almacen is 'Almacenes de repuestos';

-- Catálogo de repuestos
create table repuesto (
    id bigint generated by default as identity,
    codigo varchar(30) not null unique,
    nombre varchar(120) not null,
    categoria varchar(60),
    unidad_medida varchar(10) not null,
    precio_unitario numeric(12,2) not null,
    stock_minimo numeric(12,2) not null,
    descripcion varchar(500),
    activo boolean not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table repuesto is 'Catálogo de repuestos';

-- Stock de cada repuesto por almacén
create table inventario (
    id bigint generated by default as identity,
    almacen_id bigint not null,
    repuesto_id bigint not null,
    cantidad numeric(12,2) not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id),
    unique (almacen_id, repuesto_id)
);
comment on table inventario is 'Stock de cada repuesto por almacén';

-- Kardex: entradas, salidas y ajustes de stock
create table movimiento_inventario (
    id bigint generated by default as identity,
    fecha timestamp(6) not null,
    tipo varchar(20) not null,
    almacen_id bigint not null,
    repuesto_id bigint not null,
    cantidad numeric(12,2) not null,
    stock_resultante numeric(12,2) not null,
    referencia varchar(40),
    observacion varchar(300),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table movimiento_inventario is 'Kardex: entradas, salidas y ajustes de stock';

-- Proveedores
create table proveedor (
    id bigint generated by default as identity,
    ruc varchar(11) not null unique,
    razon_social varchar(150) not null,
    rubro varchar(80),
    contacto varchar(120),
    telefono varchar(20),
    email varchar(120),
    direccion varchar(200),
    activo boolean not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table proveedor is 'Proveedores';

-- Órdenes de compra
create table compra (
    id bigint generated by default as identity,
    codigo varchar(20) unique,
    proveedor_id bigint not null,
    almacen_id bigint not null,
    fecha_emision date not null,
    fecha_recepcion date,
    comprobante_proveedor varchar(30),
    estado varchar(20) not null,
    subtotal numeric(12,2) not null,
    igv numeric(12,2) not null,
    total numeric(12,2) not null,
    observaciones varchar(1000),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table compra is 'Órdenes de compra';

-- Detalle de órdenes de compra
create table compra_detalle (
    id bigint generated by default as identity,
    compra_id bigint not null,
    repuesto_id bigint not null,
    cantidad numeric(12,2) not null,
    precio_unitario numeric(12,2) not null,
    subtotal numeric(12,2) not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table compra_detalle is 'Detalle de órdenes de compra';

-- Cotizaciones
create table cotizacion (
    id bigint generated by default as identity,
    codigo varchar(20) unique,
    solicitud_id bigint,
    cliente_id bigint not null,
    fecha_emision date not null,
    dias_validez integer not null check (dias_validez>=1),
    estado varchar(20) not null,
    subtotal numeric(12,2) not null,
    igv numeric(12,2) not null,
    total numeric(12,2) not null,
    condiciones varchar(2000),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table cotizacion is 'Cotizaciones';

-- Detalle de cotizaciones
create table cotizacion_detalle (
    id bigint generated by default as identity,
    cotizacion_id bigint not null,
    descripcion varchar(300) not null,
    tipo_unidad varchar(30),
    modalidad varchar(20) not null,
    cantidad numeric(12,2) not null,
    precio_unitario numeric(12,2) not null,
    subtotal numeric(12,2) not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table cotizacion_detalle is 'Detalle de cotizaciones';

-- Contratos con clientes
create table contrato (
    id bigint generated by default as identity,
    codigo varchar(20) unique,
    cliente_id bigint not null,
    cotizacion_id bigint,
    contrato_anterior_id bigint,
    objeto varchar(150),
    fecha_inicio date not null,
    fecha_fin date not null,
    monto_total numeric(12,2) not null,
    estado varchar(20) not null,
    condiciones varchar(2000),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table contrato is 'Contratos con clientes';

-- Asignación de unidades y personal (evita doble asignación)
create table asignacion (
    id bigint generated by default as identity,
    unidad_id bigint not null,
    empleado_id bigint,
    origen varchar(20) not null,
    referencia varchar(20),
    fecha_inicio timestamp(6) not null,
    fecha_fin timestamp(6) not null,
    estado varchar(20) not null,
    descripcion varchar(300),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table asignacion is 'Asignación de unidades y personal (evita doble asignación)';

-- Alquileres de maquinaria
create table alquiler (
    id bigint generated by default as identity,
    codigo varchar(20) unique,
    cliente_id bigint not null,
    contrato_id bigint,
    asignacion_id bigint not null unique,
    modalidad varchar(20) not null,
    tarifa numeric(10,2) not null,
    lectura_inicial numeric(12,1),
    lectura_final numeric(12,1),
    inicio_real timestamp(6),
    fin_real timestamp(6),
    cantidad_facturable numeric(12,2),
    monto_total numeric(12,2),
    estado varchar(20) not null,
    facturado boolean not null,
    observaciones varchar(1000),
    ubicacion_obra varchar(200),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table alquiler is 'Alquileres de maquinaria';

-- Servicios de transporte de carga
create table servicio_transporte (
    id bigint generated by default as identity,
    codigo varchar(20) unique,
    cliente_id bigint not null,
    contrato_id bigint,
    asignacion_id bigint not null unique,
    modalidad varchar(20) not null,
    tarifa numeric(10,2) not null,
    lectura_inicial numeric(12,1),
    lectura_final numeric(12,1),
    inicio_real timestamp(6),
    fin_real timestamp(6),
    cantidad_facturable numeric(12,2),
    monto_total numeric(12,2),
    estado varchar(20) not null,
    facturado boolean not null,
    observaciones varchar(1000),
    solicitud_id bigint,
    origen varchar(200) not null,
    destino varchar(200) not null,
    tipo_carga varchar(150),
    peso_toneladas numeric(10,2),
    guia_remision varchar(30),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table servicio_transporte is 'Servicios de transporte de carga';

-- Órdenes de mantenimiento preventivo y correctivo
create table orden_mantenimiento (
    id bigint generated by default as identity,
    codigo varchar(20) unique,
    unidad_id bigint not null,
    tipo varchar(20) not null,
    prioridad varchar(20) not null,
    descripcion varchar(1000) not null,
    fecha_programada date not null,
    fecha_inicio timestamp(6),
    fecha_fin timestamp(6),
    tecnico_id bigint,
    estado varchar(20) not null,
    lectura_unidad numeric(12,1),
    costo_mano_obra numeric(12,2) not null,
    costo_repuestos numeric(12,2) not null,
    costo_servicios_terceros numeric(12,2) not null,
    trabajo_realizado varchar(2000),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table orden_mantenimiento is 'Órdenes de mantenimiento preventivo y correctivo';

-- Repuestos consumidos en mantenimientos
create table repuesto_utilizado (
    id bigint generated by default as identity,
    orden_id bigint not null,
    repuesto_id bigint not null,
    almacen_id bigint not null,
    cantidad numeric(12,2) not null,
    precio_unitario numeric(12,2) not null,
    subtotal numeric(12,2) not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table repuesto_utilizado is 'Repuestos consumidos en mantenimientos';

-- Comprobantes de venta (factura/boleta)
create table venta (
    id bigint generated by default as identity,
    tipo_comprobante varchar(20) not null,
    serie varchar(4),
    numero integer,
    cliente_id bigint not null,
    fecha_emision date not null,
    fecha_vencimiento date,
    fecha_pago date,
    metodo_pago varchar(30),
    estado varchar(20) not null,
    subtotal numeric(12,2) not null,
    igv numeric(12,2) not null,
    total numeric(12,2) not null,
    observaciones varchar(1000),
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table venta is 'Comprobantes de venta (factura/boleta)';

-- Detalle de comprobantes de venta
create table venta_detalle (
    id bigint generated by default as identity,
    venta_id bigint not null,
    tipo_linea varchar(20) not null,
    descripcion varchar(300) not null,
    cantidad numeric(12,2) not null,
    unidad_medida varchar(10) not null,
    precio_unitario numeric(12,2) not null,
    subtotal numeric(12,2) not null,
    alquiler_id bigint,
    servicio_id bigint,
    repuesto_id bigint,
    almacen_id bigint,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table venta_detalle is 'Detalle de comprobantes de venta';

-- Historial de posiciones GPS
create table ubicacion_gps (
    id bigint generated by default as identity,
    unidad_id bigint not null,
    latitud float(53) not null,
    longitud float(53) not null,
    velocidad float(53),
    fecha_hora timestamp(6) not null,
    referencia varchar(200),
    fuente varchar(20) not null,
    fecha_creacion timestamp(6),
    creado_por varchar(50),
    fecha_modificacion timestamp(6),
    modificado_por varchar(50),
    primary key (id)
);
comment on table ubicacion_gps is 'Historial de posiciones GPS';

-- Notificaciones y alertas por usuario
create table notificacion (
    id bigint generated by default as identity,
    usuario_id bigint not null,
    titulo varchar(150) not null,
    mensaje varchar(500) not null,
    tipo varchar(20) not null,
    enlace varchar(200),
    leida boolean not null,
    fecha timestamp(6) not null,
    clave varchar(120),
    primary key (id)
);
comment on table notificacion is 'Notificaciones y alertas por usuario';

-- Auditoría y trazabilidad de acciones
create table auditoria (
    id bigint generated by default as identity,
    fecha timestamp(6) not null,
    usuario varchar(50) not null,
    accion varchar(20) not null,
    entidad_id bigint,
    entidad varchar(60) not null,
    detalle varchar(4000),
    ip varchar(45),
    primary key (id)
);
comment on table auditoria is 'Auditoría y trazabilidad de acciones';

-- ---------------------------------------------------------------------
-- Llaves foráneas
-- ---------------------------------------------------------------------
alter table almacen add constraint fk_almacen_responsable foreign key (responsable_id) references empleado (id);
alter table alquiler add constraint fk_alquiler_asignacion foreign key (asignacion_id) references asignacion (id);
alter table alquiler add constraint fk_alquiler_cliente foreign key (cliente_id) references cliente (id);
alter table alquiler add constraint fk_alquiler_contrato foreign key (contrato_id) references contrato (id);
alter table asignacion add constraint fk_asignacion_empleado foreign key (empleado_id) references empleado (id);
alter table asignacion add constraint fk_asignacion_unidad foreign key (unidad_id) references unidad (id);
alter table compra add constraint fk_compra_almacen foreign key (almacen_id) references almacen (id);
alter table compra add constraint fk_compra_proveedor foreign key (proveedor_id) references proveedor (id);
alter table compra_detalle add constraint fk_compra_detalle_compra foreign key (compra_id) references compra (id);
alter table compra_detalle add constraint fk_compra_detalle_repuesto foreign key (repuesto_id) references repuesto (id);
alter table contacto add constraint fk_contacto_cliente foreign key (cliente_id) references cliente (id);
alter table contrato add constraint fk_contrato_cliente foreign key (cliente_id) references cliente (id);
alter table contrato add constraint fk_contrato_contrato_anterior foreign key (contrato_anterior_id) references contrato (id);
alter table contrato add constraint fk_contrato_cotizacion foreign key (cotizacion_id) references cotizacion (id);
alter table cotizacion add constraint fk_cotizacion_cliente foreign key (cliente_id) references cliente (id);
alter table cotizacion add constraint fk_cotizacion_solicitud foreign key (solicitud_id) references solicitud (id);
alter table cotizacion_detalle add constraint fk_cotizacion_detalle_cotizacion foreign key (cotizacion_id) references cotizacion (id);
alter table inventario add constraint fk_inventario_almacen foreign key (almacen_id) references almacen (id);
alter table inventario add constraint fk_inventario_repuesto foreign key (repuesto_id) references repuesto (id);
alter table movimiento_inventario add constraint fk_movimiento_inventario_almacen foreign key (almacen_id) references almacen (id);
alter table movimiento_inventario add constraint fk_movimiento_inventario_repuesto foreign key (repuesto_id) references repuesto (id);
alter table notificacion add constraint fk_notificacion_usuario foreign key (usuario_id) references usuario (id);
alter table oportunidad add constraint fk_oportunidad_campana foreign key (campana_id) references campana (id);
alter table oportunidad add constraint fk_oportunidad_cliente foreign key (cliente_id) references cliente (id);
alter table oportunidad add constraint fk_oportunidad_responsable foreign key (responsable_id) references usuario (id);
alter table oportunidad add constraint fk_oportunidad_solicitud foreign key (solicitud_id) references solicitud (id);
alter table orden_mantenimiento add constraint fk_orden_mantenimiento_tecnico foreign key (tecnico_id) references empleado (id);
alter table orden_mantenimiento add constraint fk_orden_mantenimiento_unidad foreign key (unidad_id) references unidad (id);
alter table repuesto_utilizado add constraint fk_repuesto_utilizado_almacen foreign key (almacen_id) references almacen (id);
alter table repuesto_utilizado add constraint fk_repuesto_utilizado_orden foreign key (orden_id) references orden_mantenimiento (id);
alter table repuesto_utilizado add constraint fk_repuesto_utilizado_repuesto foreign key (repuesto_id) references repuesto (id);
alter table rol_permiso add constraint fk_rol_permiso_rol foreign key (rol_id) references rol (id);
alter table servicio_transporte add constraint fk_servicio_transporte_asignacion foreign key (asignacion_id) references asignacion (id);
alter table servicio_transporte add constraint fk_servicio_transporte_cliente foreign key (cliente_id) references cliente (id);
alter table servicio_transporte add constraint fk_servicio_transporte_contrato foreign key (contrato_id) references contrato (id);
alter table servicio_transporte add constraint fk_servicio_transporte_solicitud foreign key (solicitud_id) references solicitud (id);
alter table solicitud add constraint fk_solicitud_cliente foreign key (cliente_id) references cliente (id);
alter table solicitud add constraint fk_solicitud_contacto foreign key (contacto_id) references contacto (id);
alter table ubicacion_gps add constraint fk_ubicacion_gps_unidad foreign key (unidad_id) references unidad (id);
alter table usuario add constraint fk_usuario_empleado foreign key (empleado_id) references empleado (id);
alter table usuario add constraint fk_usuario_rol foreign key (rol_id) references rol (id);
alter table venta add constraint fk_venta_cliente foreign key (cliente_id) references cliente (id);
alter table venta_detalle add constraint fk_venta_detalle_almacen foreign key (almacen_id) references almacen (id);
alter table venta_detalle add constraint fk_venta_detalle_alquiler foreign key (alquiler_id) references alquiler (id);
alter table venta_detalle add constraint fk_venta_detalle_repuesto foreign key (repuesto_id) references repuesto (id);
alter table venta_detalle add constraint fk_venta_detalle_servicio foreign key (servicio_id) references servicio_transporte (id);
alter table venta_detalle add constraint fk_venta_detalle_venta foreign key (venta_id) references venta (id);

-- ---------------------------------------------------------------------
-- Índices para las consultas más frecuentes
-- ---------------------------------------------------------------------
create index idx_gps_unidad_fecha on ubicacion_gps (unidad_id, fecha_hora);
create index idx_asignacion_unidad_fechas on asignacion (unidad_id, fecha_inicio, fecha_fin);
create index idx_asignacion_empleado_fechas on asignacion (empleado_id, fecha_inicio, fecha_fin);
create index idx_asignacion_estado on asignacion (estado);
create index idx_orden_unidad_estado on orden_mantenimiento (unidad_id, estado);
create index idx_movimiento_fecha on movimiento_inventario (fecha);
create index idx_notificacion_usuario on notificacion (usuario_id, leida);
create index idx_notificacion_clave on notificacion (usuario_id, clave);
create index idx_auditoria_fecha on auditoria (fecha);
create index idx_auditoria_entidad on auditoria (entidad, entidad_id);
create index idx_venta_fecha on venta (fecha_emision, estado);
create unique index uk_venta_comprobante on venta (tipo_comprobante, numero);
